{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    {{- $component := dict "component" "api" "Chart" .Chart "Release" .Release "Values" .Values }}
    {{- include "aura360.componentLabels" $component | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - name: http
    port: {{ .Values.api.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "aura360.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
{{- end }}
