{{- if .Values.vectordbWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectordb-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- $component := dict "component" "vectordb-worker" "Chart" .Chart "Release" .Release "Values" .Values }}
    {{- include "aura360.componentLabels" $component | nindent 4 }}
spec:
  {{- if not .Values.vectordbWorker.autoscaling.enabled }}
  replicas: {{ .Values.vectordbWorker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aura360.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: vectordb-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aura360.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: vectordb-worker
    spec:
      containers:
      - name: vectordb-worker
        image: {{ include "aura360.image" (dict "Values" .Values "repository" .Values.vectordbWorker.image.repository "tag" .Values.vectordbWorker.image.tag) }}
        imagePullPolicy: {{ .Values.vectordbWorker.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.vectordbWorker.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        resources:
          {{- toYaml .Values.vectordbWorker.resources | nindent 10 }}
{{- end }}
