{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Values.namespace }}
  labels:
    {{- $component := dict "component" "web" "Chart" .Chart "Release" .Release "Values" .Values }}
    {{- include "aura360.componentLabels" $component | nindent 4 }}
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aura360.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aura360.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: web
        image: {{ include "aura360.image" (dict "Values" .Values "repository" .Values.web.image.repository "tag" .Values.web.image.tag) }}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.web.env.PORT }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "{{ .Values.web.env.NODE_ENV }}"
        - name: PORT
          value: "{{ .Values.web.env.PORT }}"
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
{{- end }}
