name: aura_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  build_runner: ^2.8.0
  dio: ^5.9.0
  dio_smart_retry: ^6.0.0
  drift: ^2.28.1
  flutter:
    sdk: flutter
  animations: ^2.0.11
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  freezed: ^3.2.3
  get_it: ^8.2.0
  go_router: ^16.2.2
  json_serializable: ^6.11.1
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.6.1
  sqlite3_flutter_libs: ^0.5.24
  supabase_flutter: ^2.10.1
  cryptography: ^2.7.0
  postgres: ^3.5.6
  equatable: ^2.0.5
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
