apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: aura360
    meta.helm.sh/release-namespace: aura360
  creationTimestamp: "2025-11-17T01:33:21Z"
  generation: 1
  labels:
    app.kubernetes.io/component: vectordb-worker
    app.kubernetes.io/instance: aura360
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aura360
    app.kubernetes.io/version: 1.0.0
    environment: development
    helm.sh/chart: aura360-0.1.0
  name: vectordb-worker
  namespace: aura360
  resourceVersion: "547567"
  uid: 434fd592-7242-4f88-a645-7a0b8574e7cb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: vectordb-worker
      app.kubernetes.io/instance: aura360
      app.kubernetes.io/name: aura360
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: vectordb-worker
        app.kubernetes.io/instance: aura360
        app.kubernetes.io/name: aura360
    spec:
      containers:
      - env:
        - name: BROKER_URL
          value: redis://redis:6379/0
        - name: CELERY_CONCURRENCY
          value: "2"
        - name: DEFAULT_EMBEDDING_MODEL
          value: text-embedding-3-small
        - name: EMBEDDING_DIM
          value: "384"
        - name: EMBEDDING_VERSION
          value: 2025.10.27
        - name: GROBID_URL
          value: http://grobid:8070
        - name: QDRANT_GRPC
          value: qdrant:6334
        - name: QDRANT_URL
          value: http://qdrant:6333
        - name: RESULT_BACKEND
          value: redis://redis:6379/1
        - name: VECTOR_COLLECTION_NAME
          value: holistic_memory
        - name: VECTOR_DISTANCE
          value: cosine
        image: aura360prodacr.azurecr.io/aura360-vectordb-worker:latest
        imagePullPolicy: Always
        name: vectordb-worker
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-11-17T01:33:21Z"
    lastUpdateTime: "2025-11-17T01:33:21Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-11-17T01:43:22Z"
    lastUpdateTime: "2025-11-17T01:43:22Z"
    message: ReplicaSet "vectordb-worker-c8f88df9f" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
